"""remove redundant modules.resource_id, resources.module_id is now the single FK

Revision ID: 103e981786de
Revises: 3391f2c0d9ab
Create Date: 2026-09-02 12:33:42.895499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '103e981786de'
down_revision = '3391f2c0d9ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('flag_reason', sa.String(length=100), nullable=True))
        batch_op.drop_index(batch_op.f('ix_comments_id'))

    with op.batch_alter_table('modules', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('resource_id')

    with op.batch_alter_table('quizzes', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_quizzes_module_id'), ['module_id'])

    with op.batch_alter_table('ratings', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('ck_rating_score_range'), type_='check')
        batch_op.create_check_constraint(batch_op.f('ck_ratings_ck_rating_score_range'), 'score >= 1 AND score <= 5')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ratings', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('ck_ratings_ck_rating_score_range'), type_='check')
        batch_op.create_check_constraint(batch_op.f('ck_rating_score_range'), 'score >= 1 AND score <= 5')

    with op.batch_alter_table('quizzes', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_quizzes_module_id'), type_='unique')

    with op.batch_alter_table('modules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('resource_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(None, 'resources', ['resource_id'], ['id'])

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_comments_id'), ['id'], unique=False)
        batch_op.drop_column('flag_reason')

    # ### end Alembic commands ###
