"""add remaining Questly tables

Revision ID: 3391f2c0d9ab
Revises: b0e938bd03ff
Create Date: 2026-09-02 10:50:06.775954

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '3391f2c0d9ab'
down_revision = 'b0e938bd03ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('discussions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('learning_path_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('flag_reason', sa.String(length=100), nullable=True))
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=200),
               existing_nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('ix_discussions_id'))
        batch_op.create_foreign_key('fk_discussions_learning_path_id_learning_paths', 'learning_paths', ['learning_path_id'], ['id'])
        batch_op.drop_column('reply_count')
        batch_op.drop_column('path_id')

    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content_type', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('content_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('content_title', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('resolver_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('resolution_note', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('resolved_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('reason',
               existing_type=sa.TEXT(),
               type_=sa.String(length=200),
               existing_nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=8),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('ix_reports_id'))
        batch_op.create_foreign_key('fk_reports_resolver_id_users', 'users', ['resolver_id'], ['id'])
        batch_op.drop_column('updated_at')
        batch_op.drop_column('target_type')
        batch_op.drop_column('target_id')

    with op.batch_alter_table('system_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admin_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('user_agent', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('extra_data', sa.JSON(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_system_logs_id'))
        batch_op.create_foreign_key('fk_system_logs_admin_id_users', 'users', ['admin_id'], ['id'])
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('system_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=True))
        batch_op.create_index(batch_op.f('ix_system_logs_id'), ['id'], unique=False)
        batch_op.drop_column('extra_data')
        batch_op.drop_column('user_agent')
        batch_op.drop_column('admin_id')

    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('target_id', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('target_type', sa.VARCHAR(length=50), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DATETIME(), nullable=True))
        batch_op.create_index(batch_op.f('ix_reports_id'), ['id'], unique=False)
        batch_op.alter_column('status',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=8),
               existing_nullable=True)
        batch_op.alter_column('reason',
               existing_type=sa.String(length=200),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.drop_column('resolved_at')
        batch_op.drop_column('resolution_note')
        batch_op.drop_column('resolver_id')
        batch_op.drop_column('description')
        batch_op.drop_column('content_title')
        batch_op.drop_column('content_id')
        batch_op.drop_column('content_type')

    with op.batch_alter_table('discussions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('path_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('reply_count', sa.INTEGER(), nullable=True))
        batch_op.create_index(batch_op.f('ix_discussions_id'), ['id'], unique=False)
        batch_op.alter_column('status',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('title',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
        batch_op.drop_column('flag_reason')
        batch_op.drop_column('learning_path_id')

    # ### end Alembic commands ###
