"""add challenge progress table

Revision ID: f9ccdf72aa69
Revises: 8c95dd2a7a03
Create Date: 2026-09-06 12:04:00.751732

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9ccdf72aa69'
down_revision = '8c95dd2a7a03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('challenge_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('challenge_id', sa.Integer(), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenges.id'], name=op.f('fk_challenge_progress_challenge_id_challenges')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_challenge_progress_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_challenge_progress'))
    )
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('flag_reason', sa.String(length=100), nullable=True))
        batch_op.drop_index(batch_op.f('ix_comments_id'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_comments_id'), ['id'], unique=False)
        batch_op.drop_column('flag_reason')

    op.drop_table('challenge_progress')
    # ### end Alembic commands ###
